
module.exports = [
	require('./status'),
	require('./createroom'),
	require('./enterroom'),
	require('./fetchrole'),
	require('./lynch'),
	require('./skill'),
	require('./villager'),
	require('./werewolf'),
	require('./seer'),
	require('./minion'),
	require('./troublemaker'),
	require('./robber'),
	require('./drunk'),
	require('./mason'),
	require('./board'),
	require('./witch'),
	require('./alphawolf'),
	require('./dreamwolf'),
	require('./mysticwolf'),
	require('./paranormalinvestigator'),
];
